# Generated by Django 5.1.2 on 2025-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0002_alter_color_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
