# Generated by Django 5.1.2 on 2025-02-03 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_name'),
        ('items', '0003_remove_item_unique_item_constraint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='brands.brand'),
        ),
    ]
