# Generated by Django 5.1.2 on 2025-02-18 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_name'),
        ('items', '0004_alter_item_brand'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_constraint',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('description', 'price', 'size'), name='unique_item_constraint'),
        ),
    ]
