# Generated by Django 5.1.2 on 2025-02-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0003_alter_brand_name'),
        ('items', '0006_remove_item_unique_item_constraint_item_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_item_constraint',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('product_id',), name='unique_item_constraint'),
        ),
    ]
