# Generated by Django 5.1.2 on 2025-02-13 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolor',
            name='euclidean_distance',
            field=models.FloatField(default=0.0),
        ),
    ]
