# Generated by Django 5.1.2 on 2025-02-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relationships', '0002_itemcolor_euclidean_distance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcolor',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='image_url',
            field=models.URLField(unique=True),
        ),
    ]
