# Generated by Django 5.1.2 on 2025-02-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0003_alter_color_id'),
        ('items', '0004_alter_item_brand'),
        ('relationships', '0003_alter_itemcolor_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolor',
            name='real_rgb',
            field=models.CharField(default='', help_text='The original RGB from the CSV', max_length=20),
        ),
        migrations.AlterField(
            model_name='itemcolor',
            name='image_url',
            field=models.URLField(),
        ),
        migrations.AlterUniqueTogether(
            name='itemcolor',
            unique_together={('item', 'color')},
        ),
    ]
