# Generated by Django 5.1.2 on 2025-02-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_item_brand'),
        ('relationships', '0004_itemcolor_real_rgb_alter_itemcolor_image_url_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcolor',
            unique_together={('item', 'real_rgb')},
        ),
    ]
