# Generated by Django 5.1.2 on 2025-02-19 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('color', '0003_alter_color_id'),
        ('items', '0007_remove_item_unique_item_constraint_and_more'),
        ('relationships', '0005_alter_itemcolor_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemcolor',
            unique_together={('item', 'real_rgb', 'color')},
        ),
    ]
